statistics_glossary = {'2p': 'two pointers made',
	'2p%': 'two pointer conversion %',
	'2pa': 'two pointer attempts',
	'3p': 'three pointers made',
	'3p%': 'three pointer conversion %',
	'3pa': 'three pointer attempts',
	'ast': 'assists',
	'age': 'age',
	'blk': 'blocks',
	'drb': 'defense rebounds',
	'fg': 'field goals made',
	'fg%': 'field goal conversion %',
	'fga': 'field goal attempts',
	'ft': 'free throws made',
	'ft%': 'free throw conversion %',
	'fta': 'free throw attempts', 
	'g': 'games played',
	'gs': 'games started',
	'mp': 'minutes played',
	'orb': 'offensive rebounds',
	'pf': 'personal fouls',
	'pts': 'points scored',
	'pos': 'position',
	'stl': 'steals',
	'tov': 'turnovers',
	'trb': 'total rebounds',
	'efg%': 'effective field goal conversion %',
	'season': 'season',
	'team_acronym': 'team acronym',
	'team_name': 'team name'}